Importing data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('global_startup_dataset.csv')
df.head()

,startup_id,startup_name,country,headquarters_city,industry,founded_year,founders,employees,funding_stage,funding_total_usd,valuation_usd,investors,last_funding_date,status,website,is_unicorn
0,SU000001,EchoSystems,China,Beijing,SaaS,2013,Allison Hill,189,Series B,15125000,1.462000e+08,Kingsford Ventures; Hearthstone Group,2013-08-06,Active,https://www.echosystems.com,False
1,SU000002,EchoAnalytics Co.,Netherlands,Rotterdam,CleanTech / Climate,2018,Noah Rhodes,15,Series A,12607000,1.296600e+08,Kingsford Ventures; Cedarbrook Holdings,2019-02-01,Active,https://www.echoanalyticsco.com,False
2,SU000003,VertexAI,China,Shenzhen,Manufacturing Tech,2012,Angie Henderson,20,Seed,1748000,1.120000e+07,Stonegate Fund; Driftwood Partners,2018-06-28,Active,https://www.vertexai.com,False
3,SU000004,AxiomPath,Mexico,Mexico City,FoodTech,2017,Daniel Wagner; Cristian Santos,3464,IPO,988809000,5.276720e+09,Aldergate Partners; Thornwell Group; Copperlin...,2018-11-01,IPO,https://www.axiompath.com,True
4,SU000005,EchoFlow,South Africa,Cape Town,LegalTech,2020,Connie Lawrence,44,Series A,17171000,1.714400e+08,Redstone Fund; Larkspur Fund,2023-07-12,Active,https://www.echoflow.com,False

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   startup_id         8000 non-null   str
 1   startup_name       8000 non-null   str
 2   country            8000 non-null   str
 3   headquarters_city  8000 non-null   str
 4   industry           8000 non-null   str
 5   founded_year       8000 non-null   int64
 6   founders           8000 non-null   str
 7   employees          8000 non-null   int64
 8   funding_stage      8000 non-null   str
 9   funding_total_usd  8000 non-null   int64
 10  valuation_usd      5929 non-null   float64
 11  investors          7612 non-null   str
 12  last_funding_date  8000 non-null   str
 13  status             8000 non-null   str
 14  website            8000 non-null   str
 15  is_unicorn         8000 non-null   bool
dtypes: bool(1), float64(1), int64(3), str(11)
memory usage: 2.3 MB

In [4]:
df.describe(include='all')

,startup_id,startup_name,country,headquarters_city,industry,founded_year,founders,employees,funding_stage,funding_total_usd,valuation_usd,investors,last_funding_date,status,website,is_unicorn
count,8000,8000,8000,8000,8000,8000.000000,8000,8000.000000,8000,8.000000e+03,5.929000e+03,7612,8000,8000,8000,8000
unique,8000,7980,35,74,30,NaN,7883,NaN,7,NaN,NaN,6684,3562,4,7963,2
top,SU000001,QuantaLabsBK,United States,Singapore,Marketing Tech,NaN,Richard Smith,NaN,Seed,NaN,NaN,Redstone Partners,2026-07-15,Active,https://www.beaconhealthio.com,False
freq,1,2,1630,223,314,NaN,3,NaN,1902,NaN,NaN,13,13,5406,2,7103
mean,NaN,NaN,NaN,NaN,NaN,2017.698125,NaN,649.496000,NaN,1.030689e+08,6.022411e+08,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,4.281856,NaN,2044.072823,NaN,2.888948e+08,1.360115e+09,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,2011.000000,NaN,0.000000,NaN,2.100000e+04,2.000000e+05,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,2014.000000,NaN,10.000000,NaN,1.363000e+06,2.009000e+07,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN,42.000000,NaN,1.027350e+07,1.236200e+08,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,232.000000,NaN,4.868325e+07,4.936200e+08,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,2026.000000,NaN,15000.000000,NaN,1.998061e+09,1.186959e+10,NaN,NaN,NaN,NaN,NaN

In [5]:
df.isnull().sum()

startup_id              0
startup_name            0
country                 0
headquarters_city       0
industry                0
founded_year            0
founders                0
employees               0
funding_stage           0
funding_total_usd       0
valuation_usd        2071
investors             388
last_funding_date       0
status                  0
website                 0
is_unicorn              0
dtype: int64

In [8]:
df['valuation_usd'].isna().sum()

np.int64(2071)

In [10]:
df['valuation_usd'].isna().mean() * 100

np.float64(25.887500000000003)

In [11]:
df['investors'].isna().sum()

np.int64(388)

In [12]:
df['investors'].isna().mean() * 100

np.float64(4.8500000000000005)

In [13]:

!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: sqlalchemy in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.1.1)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in C:\Users\Nitis\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [14]:
from sqlalchemy import create_engine

In [15]:
username = "postgres"      # default user
password = "4250" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "Startup"    # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'Startup'.